### ISSUE TITLE
User suggestion: Entities become Biomarkers and Biomarkers become Profiles, Fingerprints or Patterns

### ISSUE THREAD

**Issue by jgeofil** [thehyve/gliobase#129]

**Comment by zhangxiaoyu11** [comment]
Entities -> Biomarkers
Biomarkers -> Profiles
Seems good if we change this way.
The word "Entities" is wired.

**Comment by nash5202** [comment]
Have referred this issue to 2 biology people. One at Princeton and other at UoPlymouth :)
