### ISSUE TITLE
Data model discussion

### ISSUE THREAD

**Issue by jgeofil** [thehyve/gliobase#4]
![blank erd 2](https://user-images.githubusercontent.com/12494787/50969255-29e9e380-14de-11e9-95a7-ab18210ecf52.png)

**Comment by zhangxiaoyu11** [comment]
In those paper show that biomarker A and biomarker B **together** is good for diagnosis also means that **just A** or **just B** is not ok?

**Comment by jgeofil** [comment]
> In those paper show that biomarker A and biomarker B **together** is good for diagnosis also means that **just A** or **just B** is not ok?

No, there could be a paper showing evidence for A+B and others just for A or just for B.

PubmedIds: P1, P2, P3

EvidenceSet[A,B]
  Evidence[A,B,P1]
  Evidence[A,B,P2]

EvidenceSet[A]
  Evidence[A,P1]
  Evidence[A,P3]

**Comment by nash5202** [comment]
Yup, Jeremy is correct about the articles that show multiple biomarkers together. However, there are also papers which looks for multiple biomarkers and concludes that each one of them separately is a biomarker for specific purposes.

**Comment by zhangxiaoyu11** [comment]
> > In those paper show that biomarker A and biomarker B **together** is good for diagnosis also means that **just A** or **just B** is not ok?
> 
> No, there could be a paper showing evidence for A+B and others just for A or just for B.
> 
> PubmedIds: P1, P2, P3
> 
> EvidenceSet[A,B]
> Evidence[A,B,P1]
> Evidence[A,B,P2]
> 
> EvidenceSet[A]
> Evidence[A,P1]
> Evidence[A,P3]

In your example here, for EvidenceSet[A] P2 is not here. Dose it mean that from P2 we can see only A+B together is good but just A is not good for the purposes?

**Comment by jgeofil** [comment]
> Yup, Jeremy is correct about the articles that show multiple biomarkers together. However, there are also papers which looks for multiple biomarkers and concludes that each one of them separately is a biomarker for specific purposes.

That's where Evidence comes in (btw maybe you have better names for these schemas/types).
An Evidence record is:
- A reference to an evidence set
- A reference to a paper
- Data about the experiment and an outcome

**Comment by jgeofil** [comment]
> > > In those paper show that biomarker A and biomarker B **together** is good for diagnosis also means that **just A** or **just B** is not ok?
> > 
> > 
> > No, there could be a paper showing evidence for A+B and others just for A or just for B.
> > PubmedIds: P1, P2, P3
> > EvidenceSet[A,B]
> > Evidence[A,B,P1]
> > Evidence[A,B,P2]
> > EvidenceSet[A]
> > Evidence[A,P1]
> > Evidence[A,P3]
> 
> In your example here, for EvidenceSet[A] P2 is not here. Dose it mean that from P2 we can see only A+B together is good but just A is not good for the purposes?

P2 has an experiment concerning A+B and an outcome for this set. It has no information about A alone.

**Comment by zhangxiaoyu11** [comment]
> > > > In those paper show that biomarker A and biomarker B **together** is good for diagnosis also means that **just A** or **just B** is not ok?
> > > 
> > > 
> > > No, there could be a paper showing evidence for A+B and others just for A or just for B.
> > > PubmedIds: P1, P2, P3
> > > EvidenceSet[A,B]
> > > Evidence[A,B,P1]
> > > Evidence[A,B,P2]
> > > EvidenceSet[A]
> > > Evidence[A,P1]
> > > Evidence[A,P3]
> > 
> > 
> > In your example here, for EvidenceSet[A] P2 is not here. Dose it mean that from P2 we can see only A+B together is good but just A is not good for the purposes?
> 
> P2 has an experiment concerning A+B and an outcome for this set. It has no information about A alone.

OK. That makes sense for me. 
For an evidence record, why there is a reference to an evidence set which is not in the diagram?

**Comment by jgeofil** [comment]
![data model](https://user-images.githubusercontent.com/12494787/50976972-89052380-14f1-11e9-8624-3eb876b1cb4c.png)

**Comment by jgeofil** [comment]
![data model 1](https://user-images.githubusercontent.com/12494787/50979518-ee0f4800-14f6-11e9-9e52-fe9655f80ad0.png)
